# /bin/bash
# author: ruandongdong

# email: ruandongdong2012@gmail.com

# path: ~/.bashrc
# run by /home/ubuntu/.profile
function parse_git_dirty {
    [[ $(git status 2> /dev/null | tail -n1) != " nothing to commit (working
    directory clean)" ]] && echo "*"
}

function parse_git_branch {
    git branch --no--color 2>/dev/null |sed -e '/^[^*]/d' -e 's/*
    \(.*\)/[\1$(parse_git_dirty)]/'
}
export PS1='\e[32:40m\u@\h\e[1:34m:\w\[\e[1:36m\]$(parse_git_branch)\[\e[0m\]\n$]]'





